(cram
 (enabled_if
  (= %{context_name} "default"))
 (deps %{bin:bob} sched.exe free.exe ../bin/cat.exe))

(executable
 (name sched)
 (modules sched)
 (libraries logs.fmt fmt fpath unix))

(executable
 (name free)
 (modules free)
 (libraries logs.fmt unix))

(test
 (name test_handshake)
 (modules test_handshake)
 (libraries logs.fmt fmt.tty bob alcotest))

(executable
 (name test_pack)
 (modules test_pack)
 (libraries alcotest bob.stream bob.pack))

(rule
 (alias runtest)
 (deps (:test test_pack.exe) (glob_files files/*))
 (action
  (run %{test} --color=always)))
